### ISSUE TITLE
How do I add social icons to the footer?

### ISSUE THREAD

**Issue by I-keep-trying** [stackbithq/stackbit-theme-exto#1]
... or for that matter, how do I change literally *anything*, any seemingly insignificant changes either directly to the code or through the /admin/ interface. 

The changes I made to the code are reflected in the /admin/ however, the site page does not update correctly. 

I am pushing my changes to my github repo first, since (another request, not as important) there is no local updating to see changes.

I checked to make sure Netlify is also updating after each push, and it seems to be working fine.

Then the social widgets are there, but the Font Awesome class names I gave them are not working for some reason. They all just look like rectangles. I made sure the `fa-whatever` exist in `fontawesome.min.css` before using them. Then I added them to `social.json` making sure to follow the same syntax as the others. 

What am I missing? 

Here's my netlify link https://panoramic-sycamore-f6876.netlify.com/
and github https://github.com/I-keep-trying/panoramic-sycamore

**Comment by TomasBankauskas** [comment]
Hey there,

the reason "Font Awesome" class names not working for you, is because this theme has only "Font Awesome" brands icon pack included. All other icons from Font Awesome pack won't work.

**Comment by I-keep-trying** [comment]
OK, thanks! 
How difficult would it be for me to add the other free Font Awesome icons?

**Comment by I-keep-trying** [comment]
Also, is the hot reload on local machine supposed to be working, or is that not a feature of this build? It's not super important, but it would be nice to see changes on my local machine, instead of having to constantly push to github in order to see any changes.

**Comment by I-keep-trying** [comment]
OK never mind about the icons, I figured it out. I just had to import the other free ones, and update `social.js` to grab the `fab` or `fas` prefix from `social.json` where I added that field.

And I also figured out that pushing to the repo is not necessary, but I do still have to stop & start the local server - ctrl + C, `gatsby develop` every time I want to see changes.
